name: openclaw
region: tor # Available: nyc, ams, sfo, sgp, lon, fra, blr, syd, tor

workers:
  - name: openclaw
    dockerfile_path: /Dockerfile
    source_dir: /
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-2gb # Minimum 2GB required - 1GB causes heap overflow
    github:
      branch: main
      deploy_on_push: true
      repo: digitalocean-labs/openclaw-appplatform
    envs:
      # ============================================================
      # REQUIRED
      # ============================================================
      - key: OPENCLAW_GATEWAY_TOKEN
        scope: RUN_TIME
        type: SECRET
      - key: STABLE_HOSTNAME
        scope: RUN_TIME
        value: openclaw

      # ============================================================
      # FEATURE FLAGS
      # Set to "true" to enable each feature, then fill in the config below
      # ============================================================
      - key: ENABLE_NGROK
        scope: RUN_TIME
        value: "false"
      - key: TAILSCALE_ENABLE
        scope: RUN_TIME
        value: "false"
      - key: ENABLE_SPACES
        scope: RUN_TIME
        value: "false"
      - key: ENABLE_UI
        scope: RUN_TIME
        value: "true"

      # ============================================================
      # NGROK - Public Tunnel Access
      # Set ENABLE_NGROK=true and provide your authtoken
      # Get token: https://dashboard.ngrok.com/get-started/your-authtoken
      # ============================================================
      - key: NGROK_AUTHTOKEN
        scope: RUN_TIME
        type: SECRET

      # ============================================================
      # TAILSCALE - Private Network Access
      # Set TAILSCALE_ENABLE=true and provide your auth key
      # Get key: https://login.tailscale.com/admin/settings/keys
      # NOTE: Mutually exclusive with ngrok
      # ============================================================
      - key: TS_AUTHKEY
        scope: RUN_TIME
        type: SECRET

      # ============================================================
      # SPACES - Data Persistence
      # Set ENABLE_SPACES=true and configure your Spaces bucket
      # Create bucket: https://cloud.digitalocean.com/spaces
      # ============================================================
      - key: RESTIC_SPACES_ACCESS_KEY_ID
        scope: RUN_TIME
        type: SECRET
      - key: RESTIC_SPACES_SECRET_ACCESS_KEY
        scope: RUN_TIME
        type: SECRET
      - key: RESTIC_SPACES_ENDPOINT
        scope: RUN_TIME
        value: tor1.digitaloceanspaces.com
      - key: RESTIC_SPACES_BUCKET
        scope: RUN_TIME
        value: openclaw-backup
      - key: RESTIC_PASSWORD
        scope: RUN_TIME
        type: SECRET

      # ============================================================
      # OPTIONAL
      # ============================================================
      - key: OPENCLAW_GATEWAY_TOKEN
        scope: RUN_TIME
        type: SECRET
      - key: GRADIENT_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: SSH_ENABLE
        scope: RUN_TIME
        value: "false"
      - key: GITHUB_USERNAME
        scope: RUN_TIME
        value: ""